blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog'))
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from collections import defaultdict

import datetime


# Create your models here.
class ArticleManage(models.Manager):
    def archive(self):
        date_list = Article.objects.datetimes('created_time', 'month', order='DESC')
        date_dict = defaultdict(list)
        for d in date_list:
            date_dict[d.year].append(d.month)
        return sorted(date_dict.items(), reverse=True)


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    objects = ArticleManage()

    title = models.CharField(verbose_name='Título', max_length=70)
    body = models.TextField(verbose_name='Texto')
    created_time = models.DateTimeField(verbose_name='Data de Criação')
    last_modified_time = models.DateTimeField(verbose_name='Última modificação')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    abstract = models.CharField(verbose_name='Resumo', max_length=54, blank=True, null=True)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    topped = models.BooleanField(default=False)

    category = models.ForeignKey('Category', verbose_name='Categoria', null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-last_modified_time']

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'article_id': self.pk})


class Category(models.Model):
    name = models.CharField('Nome', max_length=20)
    created_time = models.DateTimeField('Criado em', auto_now_add=True)
    last_modified_time = models.DateTimeField('Última Modificação', auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('Nome', max_length=20)
    created_time = models.DateTimeField('Criado em', auto_now_add=True)
    last_modified_time = models.DateTimeField('Última Modificação', auto_now=True)

    def __str__(self):
        return self.name



class BlogComment(models.Model):
    user_name = models.CharField('Usuário', max_length=100)
    user_email = models.EmailField('Email', max_length=255)
    body = models.TextField('Texto')
    created_time = models.DateTimeField('Criado em', auto_now_add=True)
    article = models.ForeignKey('Article', verbose_name='Artigo', on_delete=models.CASCADE)

    def __str__(self):
        return self.body[:20]

blog/forms.py
from django import forms
from .models import Article, BlogComment


class BlogCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ['user_name', 'user_email', 'body']
        widgets = {
            # <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "username",
                'aria-describedby': "sizing-addon1",
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "user_email",
                'aria-describedby': "sizing-addon1",
            }),
            'body': forms.Textarea(attrs={'placeholder': 'texto'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from blog.models import Article, Category, Tag
import markdown2
from .models import BlogComment
from .forms import BlogCommentForm


# Create your views here.
class IndexView(ListView):
    template_name = "blog-clean/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog-clean/detail.html"
    context_object_name = "article"
    pk_url_kwarg = 'article_id'

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'], )
        return obj


    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()
        kwargs['form'] = BlogCommentForm()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(category=self.kwargs['cate_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)


class ArchiveView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        article_list = Article.objects.filter(created_time__year=year, created_time__month=month)
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(ArchiveView, self).get_context_data(**kwargs)



class CommentPostView(FormView):
    form_class = BlogCommentForm
    template_name = 'blog/detail.html'

    def form_valid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        comment = form.save(commit=False)
        comment.article = target_article
        comment.save()
        self.success_url = target_article.get_absolute_url()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form):
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        return render(self.request, 'blog/detail.html', {
            'form': form,
            'article': target_article,
            'comment_list': target_article.blogcomment_set.all(),
        })

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Thuran's Blog</title>
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pygments/github.css' %}">
</head>
<body>
<div id="header">
    <div id="header-warp">
        <a href="{% url 'blog:index' %}"id="logo"></a>
        <ul id="header-nav">
            <li><a href="{% url 'blog:index' %}">Home</a></li>
        </ul>
        <div id="header-right" class="login">
            <div id="user-info">
                <span id="dropdown-button">Login</span>
            </div>
        </div>
    </div>
</div>

{% block content %}{% endblock %}

<div id="footer" class="noselect">
    <ul id="ft-links">
        <li><a href="" target="_blank">Agradecimentos</a></li>
    </ul>
    <ul id="ft-about-links">
        <li><a href="" target="_blank">Links</a></li>
    </ul>
    <div id="copyright">&copy; djangoBlog</div>
</div>

<script type="text/javascript" src="{% static 'blog/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/blog-clean/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Thuran's Blog</title>
    <link rel="stylesheet" href="{% static 'clean/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'clean/css/clean-blog.min.css' %}">
    <link rel="stylesheet" href="{% static 'clean/vendor/font-awesome/css/font-awesome.min.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
 <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">Diego Thuran</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Sobre</a>
                    </li>
                    <li>
                        <a href="#">Trending</a>
                    </li>
                    <li>
                        <a href="#">Contato</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>



{% block body %}
{% endblock %}

<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src={% static "clean/vendor/jquery/jquery.min.js" %}></script>

    <!-- Bootstrap Core JavaScript -->
    <script src={% static "clean/vendor/bootstrap/js/bootstrap.min.js" %}></script>

    <!-- Contact Form JavaScript -->
    <script src={% static 'clean/js/jqBootstrapValidation.js' %}></script>
    <script src={% static 'clean/js/contact_me.js' %}></script>

    <!-- Theme JavaScript -->
    <script src={% static 'clean/js/clean-blog.min.js' %}></script>
</body>

templates/blog-clean/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">Detalhes do comentário:</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">Enviar</button>
        </form>
        <p class="comment-count">Este post possui {{ 0 }} comentários</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

templates/blog-clean/detail.html
{% extends 'blog-clean/base.html' %}
{% load staticfiles %}
{% block body %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static '/clean/img/post-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">

                    </div>
                </div>
            </div>
        </div>
    </header>
    <article>
    <div class="container">
            <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time}}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog-clean/comment.html' %}
    </div>
    </div>
    </article>
{% endblock %}

templates/blog-clean/index.html
{% extends 'blog-clean/base.html' %}
{% load staticfiles %}
{% block body %}
     <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static '/clean/img/home-bg.jpg'%})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Diego Thuran</h1>
                        <hr class="small">
                        <span class="subheading">DPPDI</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
<!-- Main Content -->
    <div class="container">
        <div class="row">
            {% load paginate_tags %}
            {% paginate article_list 2 %}
            {% for article in article_list %}
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-preview">
                    <a href="{% url 'blog:detail' article.pk %}">
                        <h2 class="post-title">
                            {{ article.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ article.abstract }}
                        </h3>
                    </a>
                    <p class="post-meta">Publicado em {{ article.created_time }}</p>
                </div>
                </div>
            {% endfor %}
            {% include 'blog-clean/pagination.html' %}

        </div>
    </div>
{% endblock %}

templates/blog-clean/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>

templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">Home</a></li>
                            <li>&gt;</li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title=""
                                           rel="category">{{ article.category.name }}</a>
                                    </li>
                                </ul>
                            </li>
                            <li>&gt;</li>
                            <li class="title-active"><a href="{% url 'blog:detail' article.pk %}"
                                                        rel="bookmark">{{ article.title }}</a>
                            </li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time}}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>Categorias:</li>
                            {% for category in category_list %}
                                <li class="cat-item"><a
                                        href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% load paginate_tags %}
                        {% paginate article_list 2 %}
                        {% for article in article_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title"><a
                                            href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h1>
                                </div>
                                <div class="post-bd">
                                    <!-- 	<p><a href=""><img src="" alt=""></a></p> -->
                                    <p>{{ article.abstract }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="{% url 'blog:detail' article.id %}" class="more">Detalhes</a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>Tags:</h3>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3>Arquivo：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} </p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}